-- AlterEnum
ALTER TYPE "MOTStatus" ADD VALUE 'NA';

-- AlterTable
ALTER TABLE "CompanyVehicles" ALTER COLUMN "MOTdate" SET DEFAULT '',
ALTER COLUMN "MOTdays" SET DEFAULT 0,
ALTER COLUMN "MOTstatus" SET DEFAULT 'Valid',
ALTER COLUMN "TAXdate" SET DEFAULT '',
ALTER COLUMN "TAXdays" SET DEFAULT 0,
ALTER COLUMN "TAXstatus" SET DEFAULT 'Taxed';
